services:
  nginx:
    build:
      context: requirements/nginx/.
      args:
        - CRED_PATH
        - CRED_CERT
        - CRED_KEY
        - COUNTRY
        - STATE
        - LOCALITY
        - ORGANIZATION
        - ORG_UNIT
        - COMMON_NAME
    container_name: nginx
    restart: on-failure
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - v_web:/var/www/html
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    networks:
      - inception
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - v_web:/var/www/html
    env_file:
      - .env
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - v_db:/var/lib/mysql
    env_file:
      - .env

volumes:
  v_web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  v_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

networks:
  inception:
    driver: bridge